name: Deploy
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: /
        remote_path: /var/www/slow_server/
        remote_host: 145.239.253.165
        remote_user: mark
        remote_key: ${{ secrets.SSH_KEY }}
